services:
  smb:
    build:
      context: ./smb
    container_name: smb-server
    hostname: smb-edu
    ports:
      - "10139:139"
      - "10445:445"
      - "10137:137/udp"
      - "10138:138/udp"
    networks:
      hacklabEdu:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  snmp:
    build:
      context: ./snmp
    container_name: snmp-server
    hostname: snmp-edu
    ports:
      - "10161:161/udp"
    networks:
      hacklabEdu:
        ipv4_address: 172.20.0.20
    restart: unless-stopped

  dns:
    build:
      context: ./dns
    container_name: dns-server
    hostname: dns-edu
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
    networks:
      hacklabEdu:
        ipv4_address: 172.20.0.30
    restart: unless-stopped

networks:
  hacklabEdu:
    name: hacklabEdu
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
