options {
    directory "/var/cache/bind";

    // Escuchar consultas en todas las interfaces en el puerto 53
    listen-on port 53 { any; };
    listen-on-v6 { none; };

    // Permitir consultas desde cualquier origen (necesario para el laboratorio)
    allow-query { any; };

    // Deshabilitar recursión para comportarse puramente como servidor autoritativo
    recursion no;

    // Permitir consultas de transferencia de zona por defecto en la sección options
    allow-transfer { any; };

    dnssec-validation auto;
};

include "/etc/bind/named.conf.local";
