# Escuchar en el puerto UDP 161 en todas las interfaces IPv4
agentaddress udp:161

# Definir una vista restringida 'labview' para evitar el escaneo del Host Resources MIB (.1.3.6.1.2.1.25)
# que contiene bugs y causa crasheos de segmentación en contenedores al intentar escanear montajes.
# Solo incluimos el árbol de Sistema (.1.3.6.1.2.1.1) y el árbol de Interfaces (.1.3.6.1.2.1.2).
view   labview  included   .1.3.6.1.2.1.1
view   labview  included   .1.3.6.1.2.1.2

# Configurar comunidad de lectura 'public' restringida a la vista 'labview' para todo origen
rocommunity public default -V labview

# Datos del sistema para la enumeración educativa (pistas y banderas CTF)
syslocation DataCenter Piso 2 - FLAG{snmp_community_public_sysdescr_leak}
syscontact admin@emartinex.local
sysName snmp-edu.emartinex.local
